# Generated by Django 6.0.2 on 2026-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bot', '0002_remove_workinghour_hour_workinghour_hour_end_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='фото послуги'),
        ),
    ]
