# Generated by Django 6.0.2 on 2026-05-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bot', '0003_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_nickname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='interval',
            field=models.IntegerField(choices=[(10, '10 хв'), (15, '15 хв'), (20, '20 хв'), (30, '30 хв'), (45, '45 хв'), (60, '60 хв'), (90, '90 хв'), (120, '120 хв'), (150, '150 хв')], default=60, verbose_name='Інтервал'),
        ),
    ]
